import numpy as np

from typing import Tuple

COLUMNS_NBYTES: int

class DataFrameF64:
    @staticmethod
    def new(
        index: np.ndarray,
        columns: np.ndarray,
        values: np.ndarray,
    ) -> DataFrameF64: ...
    @property
    def index(self) -> np.ndarray: ...
    @property
    def columns(self) -> np.ndarray: ...
    @property
    def values(self) -> np.ndarray: ...
    @property
    def shape(self) -> Tuple[int, int]: ...
    def with_data(self, values: np.ndarray) -> DataFrameF64: ...
    def mean_axis1(self) -> np.ndarray: ...
    def corr_with_axis1(self, other: np.ndarray) -> np.ndarray: ...
    def save(self, path: str) -> None: ...
    @staticmethod
    def load(path: str) -> DataFrameF64: ...
