import numpy as np

from . import DataFrameF64

def new(index: np.ndarray, columns: np.ndarray, data: np.ndarray) -> DataFrameF64: ...
def shape(df: DataFrameF64) -> tuple[int, int]: ...
def rows(df: DataFrameF64, indices: np.ndarray) -> DataFrameF64: ...
def index(df: DataFrameF64) -> np.ndarray: ...
def columns(df: DataFrameF64) -> np.ndarray: ...
def values(df: DataFrameF64) -> np.ndarray: ...
